import React from 'react';
import {
  AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell,
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend
} from 'recharts';

interface ChartsGridProps {
  trendsData: { date: string; volume: number; fraudAlerts: number; avgRisk: number }[];
  riskDistribution: { name: string; value: number; color: string }[];
  analyticsData?: {
    topCountries: { country: string; total: number; fraudulent: number }[];
    topCategories: { category: string; alerts: number; totalVolume: number }[];
    fraudByHour: { hour: string; count: number }[];
  };
}

export const ChartsGrid: React.FC<ChartsGridProps> = ({ trendsData, riskDistribution, analyticsData }) => {
  // Remap pie chart colors to natural tones if needed
  const naturalPieColors = ['#8BA888', '#DDE5B6', '#CB997E', '#9E2A2B', '#A68A64'];

  return (
    <div className="space-y-6">
      {/* Row 1: Volume & Alerts Over Time */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Chart 1: Transaction Volume & Average Risk Score */}
        <div className="bg-white p-6 rounded-2xl border border-[#EBE7DF] shadow-xs">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h4 className="font-serif font-bold text-base text-[#2C3327]">Transaction Volume & Velocity</h4>
              <p className="text-xs text-[#6B705C]">Processed transaction throughput per interval</p>
            </div>
            <span className="text-[10px] font-mono px-3 py-1 rounded-full bg-[#F3F1EB] text-[#6B705C] font-semibold border border-[#EBE7DF]">
              Volume Trend
            </span>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={trendsData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <defs>
                  <linearGradient id="volumeGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#8BA888" stopOpacity={0.4} />
                    <stop offset="95%" stopColor="#8BA888" stopOpacity={0.0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#EBE7DF" />
                <XAxis dataKey="date" tick={{ fontSize: 11, fill: '#6B705C' }} />
                <YAxis tick={{ fontSize: 11, fill: '#6B705C' }} />
                <Tooltip
                  contentStyle={{ backgroundColor: '#2C3327', border: '1px solid #3D4035', borderRadius: '12px', color: '#FAF9F6', fontSize: '12px' }}
                />
                <Area type="monotone" dataKey="volume" stroke="#8BA888" strokeWidth={2.5} fillOpacity={1} fill="url(#volumeGrad)" name="Txn Count" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Chart 2: Fraud Alerts Generated */}
        <div className="bg-white p-6 rounded-2xl border border-[#EBE7DF] shadow-xs">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h4 className="font-serif font-bold text-base text-[#2C3327]">Fraud Alerts & Incidents</h4>
              <p className="text-xs text-[#6B705C]">Security escalations generated by Rule Engine</p>
            </div>
            <span className="text-[10px] font-mono px-3 py-1 rounded-full bg-[#F5DFDC] text-[#9E2A2B] font-semibold border border-[#9E2A2B]/30">
              Surveillance
            </span>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={trendsData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#EBE7DF" />
                <XAxis dataKey="date" tick={{ fontSize: 11, fill: '#6B705C' }} />
                <YAxis tick={{ fontSize: 11, fill: '#6B705C' }} />
                <Tooltip
                  contentStyle={{ backgroundColor: '#2C3327', border: '1px solid #3D4035', borderRadius: '12px', color: '#FAF9F6', fontSize: '12px' }}
                />
                <Bar dataKey="fraudAlerts" fill="#CB997E" radius={[6, 6, 0, 0]} name="Fraud Alerts" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Row 2: Risk Distribution & Fraud by Country */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Chart 3: Risk Score Distribution (0-100) */}
        <div className="bg-white p-6 rounded-2xl border border-[#EBE7DF] shadow-xs">
          <div className="mb-4">
            <h4 className="font-serif font-bold text-base text-[#2C3327]">Risk Severity Distribution</h4>
            <p className="text-xs text-[#6B705C]">Transactions mapped to 0-100 score bands</p>
          </div>
          <div className="h-64 flex items-center justify-center">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={riskDistribution}
                  cx="50%"
                  cy="50%"
                  innerRadius={55}
                  outerRadius={80}
                  paddingAngle={4}
                  dataKey="value"
                >
                  {riskDistribution.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={naturalPieColors[index % naturalPieColors.length] || entry.color} />
                  ))}
                </Pie>
                <Tooltip
                  contentStyle={{ backgroundColor: '#2C3327', border: '1px solid #3D4035', borderRadius: '12px', color: '#FAF9F6', fontSize: '12px' }}
                />
                <Legend verticalAlign="bottom" height={36} iconSize={8} wrapperStyle={{ fontSize: '11px', color: '#6B705C' }} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Chart 4: Fraud by Country */}
        <div className="bg-white p-6 rounded-2xl border border-[#EBE7DF] shadow-xs">
          <div className="mb-4">
            <h4 className="font-serif font-bold text-base text-[#2C3327]">Fraud by Region</h4>
            <p className="text-xs text-[#6B705C]">Suspicious incidents cross-referenced by origin country</p>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={analyticsData?.topCountries || []}
                layout="vertical"
                margin={{ top: 5, right: 10, left: 15, bottom: 5 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="#EBE7DF" />
                <XAxis type="number" tick={{ fontSize: 10, fill: '#6B705C' }} />
                <YAxis dataKey="country" type="category" tick={{ fontSize: 10, fill: '#6B705C' }} width={80} />
                <Tooltip
                  contentStyle={{ backgroundColor: '#2C3327', border: '1px solid #3D4035', borderRadius: '12px', color: '#FAF9F6', fontSize: '12px' }}
                />
                <Bar dataKey="fraudulent" fill="#A68A64" radius={[0, 6, 6, 0]} name="Fraud Incidents" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Chart 5: Fraud by Merchant Category */}
        <div className="bg-white p-6 rounded-2xl border border-[#EBE7DF] shadow-xs">
          <div className="mb-4">
            <h4 className="font-serif font-bold text-base text-[#2C3327]">Target Merchant Sectors</h4>
            <p className="text-xs text-[#6B705C]">High-vulnerability merchant category codes (MCCs)</p>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={analyticsData?.topCategories || []}
                layout="vertical"
                margin={{ top: 5, right: 10, left: 15, bottom: 5 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="#EBE7DF" />
                <XAxis type="number" tick={{ fontSize: 10, fill: '#6B705C' }} />
                <YAxis dataKey="category" type="category" tick={{ fontSize: 9, fill: '#6B705C' }} width={95} />
                <Tooltip
                  contentStyle={{ backgroundColor: '#2C3327', border: '1px solid #3D4035', borderRadius: '12px', color: '#FAF9F6', fontSize: '12px' }}
                />
                <Bar dataKey="alerts" fill="#8BA888" radius={[0, 6, 6, 0]} name="Triggered Alerts" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
  );
};
